### ISSUE TITLE
"WFLYSRV0153: Failed to process phase STRUCTURE of deployment \"keycloak-to-rabbit-1.0.jar\"

### ISSUE THREAD

**Issue by manolovisoromero** [aznamier/keycloak-event-listener-rabbitmq#4]
Hello, 
first of all thanks for making this, it's exactly what I needed for my project.

Now, I tried installing this on my running Keycloak container. I downloaded the jar and put it in the right folder and i created the environment variables like u said. I get however this error when i check the image output.

```Event listener 'keycloak-to-rabbitmq' registered, but provider not found``` and the error in the title.

Do you know how I can fix this?

**Comment by aznamier** [comment]
Hello, thank you for your comment.

What version of Keycloak are you using? Have you checked that file in docker container is not corrupted?

So far I have been running that in a docker container without any problems on Keycloak 10, 11, 12, 13.0.0

**Comment by manolovisoromero** [comment]
I am running 12.0.4
And for the corruption, I downloaded it twice using curl -O so I guess it's not corrupted.
As for the exact error:
```11:39:05,078 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-6) MSC000001: Failed to start service jboss.deployment.unit."keycloak-to-rabbit-1.0.jar".STRUCTURE: org.jboss.msc.service.StartException in service jboss.deployment.unit."keycloak-to-rabbit-1.0.jar".STRUCTURE: WFLYSRV0153: Failed to process phase STRUCTURE of deployment "keycloak-to-rabbit-1.0.jar"

at org.jboss.as.server@13.0.3.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:189)

at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)

at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)

at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)

at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)

at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)

at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)

at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)

at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYSRV0160: Failed to mount deployment content

at org.jboss.as.server@13.0.3.Final//org.jboss.as.server.deployment.module.DeploymentRootMountProcessor.deploy(DeploymentRootMountProcessor.java:95)

at org.jboss.as.server@13.0.3.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:182)

... 8 more

Caused by: java.util.zip.ZipException: zip END header not found

at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1581)

at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1476)

at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1483)

at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1288)

at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1251)

at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732)

at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:849)

at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)

at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)

at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)

at java.base/java.util.jar.JarFile.<init>(JarFile.java:319)

at java.base/java.util.jar.JarFile.<init>(JarFile.java:285)

at org.jboss.vfs@3.2.15.Final//org.jboss.vfs.spi.JavaZipFileSystem.<init>(JavaZipFileSystem.java:90)

at org.jboss.vfs@3.2.15.Final//org.jboss.vfs.spi.JavaZipFileSystem.<init>(JavaZipFileSystem.java:77)

at org.jboss.vfs@3.2.15.Final//org.jboss.vfs.VFS.mountZip(VFS.java:386)

at org.jboss.vfs@3.2.15.Final//org.jboss.vfs.VFS.mountZip(VFS.java:410)

at org.jboss.as.server@13.0.3.Final//org.jboss.as.server.deployment.DeploymentMountProvider$Factory$ServerDeploymentRepositoryImpl.mountDeploymentContent(DeploymentMountProvider.java:108)

at org.jboss.as.server@13.0.3.Final//org.jboss.as.server.deployment.module.DeploymentRootMountProcessor.deploy(DeploymentRootMountProcessor.java:91)

... 9 more```

I didn't notice the error concerning some zip.

How did you add the jar to your container? Like I did?

**Comment by manolovisoromero** [comment]
I looked around on the internet and apparently I had to add -L to the curl to prevent a redirect or something. The jar is working fine now. However, I'm getting connection issues now. Rabbitmq and keycloak both run in their own docker image, does the networking config u provided still apply to this scenario? I'm getting connection refused error from keycloak now.
localhost isn't working and the ip address given to the image isn't either. 
Any tips?

**Comment by aznamier** [comment]
That is great. Yes as you have discovered your downloaded file was corrupted. The zip error is the indication of the problem with jar (as every jar uses zip compression). And yes -L for curl allows to follow redirects from GitHub's file to be downloaded.

My setup for adding the jar to the container is that I use custom Dockerfile that extends Keycloak's Dockerfile and there I do append the jar with curl.

**Comment by aznamier** [comment]
About the connectivity issue, I also run Rabbit in a separate container to Keycloak, so that is exactly how it should work 100%. However you didn't provide any details for the orcherstrator you are using (Rancher, Kubernetes, etc) so hard to give any tips. But it does seem its a connectivity/docker setup issue at this moment.

**Comment by manolovisoromero** [comment]
![image](https://user-images.githubusercontent.com/42765643/119485944-fa0ea400-bd57-11eb-9262-1a2eb3920237.png)
These are the ports exposed on my rabbitmq image

![image](https://user-images.githubusercontent.com/42765643/119486021-0e52a100-bd58-11eb-8447-40ad427f6686.png)
These are the environment variables of the keycloak container.

As of now I am just running these images locally on my pc, not orchestrator here.

And this is the error i'm getting in the keycloak image 
```
10:49:10,489 ERROR [stderr] (default task-1) keycloak-to-rabbitmq ERROR sending message: KK.EVENT.CLIENT.Twitch2.ERROR.Twitch2Frontend.LOGIN_ERROR

10:49:10,489 ERROR [stderr] (default task-1) java.net.ConnectException: Connection refused (Connection refused)
````

**Comment by aznamier** [comment]
As far as I can tell, the `localhost` config in Keycloak env variable would refer to Keycloak container itself so that would not work.

I think you are mapping rabbit port 15672 to expose RabbitMQ on your laptop's IP:15672 or maybe 0.0.0.0:15672
Not sure maybe that mapped 0.0.0.0 needs to be the actual ip.
Then what can be tried here is to setup `KK_TO_RMQ_URL` to the ip of your laptop

Aside of that I think this is not a keycloak-to-rabbitmq issue, but the docker installation config, so I am going to close this support ticket.
